In [1]:
import numpy as np

In [2]:
np.__version__

'2.1.1'

## Create & Read

#### 1D Array

In [3]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(6,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim

1

In [8]:
arr1.size

6

#### 2D Array

In [9]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [10]:
arr2.ndim

2

In [11]:
arr2.shape # (row, col)

(2, 3)

In [12]:
arr2.dtype

dtype('int64')

In [13]:
arr1.size

6

#### 3D Array

In [14]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[1, 4, 5], [6, 7, 4]]])

In [15]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [16]:
arr3.ndim

3

In [17]:
arr3.shape

(3, 2, 3)

In [18]:
# (3, 2, 3)

In [19]:
arr3.size

18

### Create random array

In [20]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.47167238, 0.67323202, 0.38505326],
        [0.94838402, 0.22642082, 0.27701074]],

       [[0.19538602, 0.86066451, 0.98560404],
        [0.50307945, 0.65939661, 0.7724165 ]],

       [[0.03828227, 0.86667471, 0.69499179],
        [0.42823434, 0.37675472, 0.79259075]]])

In [21]:
randomArr.dtype

dtype('float64')

In [22]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
zeroes.ndim

3

In [24]:
full = np.full((3, 2, 3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [25]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [27]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [28]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [29]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [30]:
arr3[1][0][1]

np.int64(5)

In [31]:
arr3[1, 0, 1]

np.int64(5)

### Update & Delete

In [32]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [33]:
a1

array([[[0.54216876, 0.29345081],
        [0.18912442, 0.08181549],
        [0.3374609 , 0.1995443 ]],

       [[0.2387095 , 0.98426505],
        [0.32220841, 0.85445668],
        [0.63379627, 0.53033655]]])

In [34]:
a2

array([[[0.92541715, 0.22308002],
        [0.91140082, 0.92237989],
        [0.97260856, 0.64482886]],

       [[0.02291464, 0.08953673],
        [0.13669674, 0.42327333],
        [0.03769962, 0.84108041]]])

#### Basic Math Operarations

In [35]:
np.add(a1, a2)

array([[[1.46758591, 0.51653083],
        [1.10052525, 1.00419538],
        [1.31006946, 0.84437315]],

       [[0.26162414, 1.07380178],
        [0.45890515, 1.27773   ],
        [0.67149589, 1.37141697]]])

In [36]:
np.subtract(a1, a2)

array([[[-0.38324839,  0.07037079],
        [-0.7222764 , -0.84056441],
        [-0.63514766, -0.44528456]],

       [[ 0.21579486,  0.89472832],
        [ 0.18551168,  0.43118335],
        [ 0.59609664, -0.31074386]]])

In [37]:
np.divide(a1, a2)

array([[[ 0.58586418,  1.31545091],
        [ 0.2075096 ,  0.08870042],
        [ 0.34696477,  0.30945311]],

       [[10.41733538, 10.99286336],
        [ 2.35710392,  2.01868775],
        [16.81174052,  0.63054203]]])

In [38]:
np.multiply(a1, a2)

array([[[0.50173227, 0.06546301],
        [0.17236816, 0.07546496],
        [0.32821736, 0.12867192]],

       [[0.00546994, 0.08812788],
        [0.04404484, 0.36166872],
        [0.02389388, 0.44605569]]])

#### Statistical operations

In [39]:
sqrt = np.sqrt(25)
abs = np.abs(-2)
power = np.power(2,8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [40]:
sqrt

np.float64(5.0)

In [41]:
abs

np.int64(2)

In [42]:
power

np.int64(256)

In [43]:
log

np.float64(3.2188758248682006)

In [44]:
mins

np.float64(0.08181548725247112)

In [45]:
maxs

np.float64(0.9726085582217473)

#### Update

In [46]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [47]:
arr3[0, 0, 2] = 500
arr3

array([[[  1,   4, 500],
        [  6,   7,   4]],

       [[  3,   5,   4],
        [  5,   8,   7]],

       [[  1,   4,   5],
        [  6,   7,   4]]])

In [48]:
arr3.sort()
arr3

array([[[  1,   4, 500],
        [  4,   6,   7]],

       [[  3,   4,   5],
        [  5,   7,   8]],

       [[  1,   4,   5],
        [  4,   6,   7]]])

In [49]:
# Reshape
arr3.shape

(3, 2, 3)

In [50]:
arr3_reshape = arr3.reshape((2, 3, -1))
arr3_reshape

array([[[  1,   4, 500],
        [  4,   6,   7],
        [  3,   4,   5]],

       [[  5,   7,   8],
        [  1,   4,   5],
        [  4,   6,   7]]])

In [51]:
arr3_reshape.shape

(2, 3, 3)

#### Appending & Inserting

In [52]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [53]:
# Create a new array
new_array = np.ones((3, 2, 3))
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [54]:
appd = np.append(zeroes, new_array, axis=0) # axis 0 = row, axis 1 = column
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [55]:
# Insert

In [56]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
new_array

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [58]:
inserted_array = np.insert(zeroes, 2, new_array, axis=0)
inserted_array

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [59]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.14549024, 0.24028239, 0.60278203],
        [0.24639894, 0.88229001, 0.92452248]],

       [[0.16752035, 0.49247574, 0.27331444],
        [0.65205108, 0.66460927, 0.97084882]],

       [[0.19241511, 0.05206536, 0.84265823],
        [0.41041168, 0.93683854, 0.02779595]]])

In [60]:
# delete the array
arr5 = np.delete(arr4, 0, axis=1)

In [61]:
arr5

array([[[0.24639894, 0.88229001, 0.92452248]],

       [[0.65205108, 0.66460927, 0.97084882]],

       [[0.41041168, 0.93683854, 0.02779595]]])

In [62]:
np.save("new_array", arr5)

In [63]:
np.load("new_array.npy")

array([[[0.24639894, 0.88229001, 0.92452248]],

       [[0.65205108, 0.66460927, 0.97084882]],

       [[0.41041168, 0.93683854, 0.02779595]]])